"""Generate a one-page PDF report for a single image analysis."""

from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path

import numpy as np
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _composite_preview(image: np.ndarray, masks: np.ndarray) -> Image.Image:
    """Compose grayscale image + colored mask overlay into a PIL image."""
    if image.ndim == 2:
        rgb = np.stack([image] * 3, axis=-1)
    else:
        rgb = image.copy()

    overlay = np.zeros_like(rgb)
    rng = np.random.default_rng(0)
    n = int(masks.max()) + 1
    if n > 1:
        palette = rng.integers(60, 230, size=(n, 3), dtype=np.uint8)
        palette[0] = 0
        overlay = palette[masks].astype(np.uint8)

    blended = (0.6 * rgb + 0.4 * overlay).clip(0, 255).astype(np.uint8)
    blended[masks == 0] = rgb[masks == 0]
    return Image.fromarray(blended)


def _histogram_png(
    areas: list[float],
    label: str,
    bins: int = 30,
) -> io.BytesIO:
    """Render a histogram of areas as PNG bytes (uses matplotlib lazily)."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(6, 3), dpi=110)
    ax.hist(areas, bins=bins, color="#5388c8", edgecolor="white")
    ax.set_xlabel(label)
    ax.set_ylabel("count")
    ax.set_title("Colony size distribution")
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    buf.seek(0)
    return buf


def write_pdf_report(
    output_path: Path,
    *,
    image: np.ndarray,
    masks: np.ndarray,
    metrics: list[dict],
    image_name: str,
    elapsed_seconds: float,
    engine_name: str,
    scale_um_per_px: float | None = None,
) -> None:
    """Render a one-page PDF report and write it to ``output_path``."""
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        title=f"Petrilya report — {image_name}",
    )
    story = []

    story.append(Paragraph("<b>Petrilya — Colony Analysis Report</b>", styles["Title"]))
    story.append(Spacer(1, 0.3 * cm))

    meta_rows = [
        ["Image", image_name],
        ["Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Engine", engine_name],
        ["Inference time", f"{elapsed_seconds:.2f} s"],
        ["Colonies found", str(len(metrics))],
    ]
    if scale_um_per_px:
        meta_rows.append(["Scale", f"{scale_um_per_px:.4f} um/px"])

    meta_table = Table(meta_rows, colWidths=[4 * cm, 12 * cm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 0.5 * cm))

    # preview
    preview = _composite_preview(image, masks)
    preview.thumbnail((1200, 1200))
    preview_buf = io.BytesIO()
    preview.save(preview_buf, format="PNG")
    preview_buf.seek(0)
    story.append(RLImage(preview_buf, width=16 * cm, height=16 * cm * preview.size[1] / preview.size[0]))
    story.append(Spacer(1, 0.4 * cm))

    # histogram
    if metrics:
        if scale_um_per_px and "area_um2" in metrics[0]:
            areas = [m["area_um2"] for m in metrics]
            label = "Area (um^2)"
        else:
            areas = [m["area_px"] for m in metrics]
            label = "Area (px)"
        hist = _histogram_png(areas, label)
        story.append(RLImage(hist, width=14 * cm, height=7 * cm))

    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            "<font size=8 color='grey'>Generated by Petrilya. "
            "Open-source: github.com/petrilya-app/petrilya-core</font>",
            styles["Normal"],
        )
    )

    doc.build(story)
